# Generated by Django 4.2.16 on 2024-11-16 08:48

import authors.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='passcode',
            field=models.CharField(help_text='Your passcode must be a combination of 6 digits', max_length=6, validators=[django.core.validators.MinLengthValidator(6), authors.validators.NumberLengthValidator()]),
        ),
    ]
